sudo: required
services:
  - docker

before_install:
  - docker build -t vafrcor/complex-client-test -f ./client/Dockerfile.dev ./client


script:
  - docker run -e CI=true vafrcor/complex-client-test npm run test -- --coverage

after_success:
  - docker build -t vafrcor/complex-client ./client
  - docker build -t vafrcor/complex-nginx ./nginx
  - docker build -t vafrcor/complex-server ./server
  - docker build -t vafrcor/complex-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push vafrcor/complex-client
  - docker push vafrcor/complex-nginx
  - docker push vafrcor/complex-server
  - docker push vafrcor/complex-worker
