apiVersion: skaffold/v2alpha1
kind: Config
build:
  local:
    push: false
  artifacts:
    - image: vafrcor/complex-client
      context: client
      docker:
        dockerfile: Dockerfile.dev
      sync:
        infer:
          - '***/*.js'
          - '***/*.css'
          - '***/*.html'
deploy:
  kubectl:
    manifests:
      - k8s/client-deployment.yaml
