name: Docker

on:
  push:
    # Publish `master` as Docker `latest` image.
    branches:
      - master

    # Publish `v1.2.3` tags as releases.
    tags:
      - v*

  # Run tests for any PRs.
  # pull_request:

env:
  # TODO: Change variable to your image's name.
  IMAGE_NAME: image_example_name

jobs:
  # Run tests.
  # See also https://docs.docker.com/docker-hub/builds/automated-testing/
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Run tests
        run: |
          docker build -t vafrcor/complex-client-test -f ./client/Dockerfile.dev ./client
          docker run -e CI=true vafrcor/complex-client-test npm run test -- --coverage

  # Push image to Docker Hub
  push:
    # Ensure test job passes before pushing image.
    needs: test

    runs-on: ubuntu-latest
    if: github.event_name == 'push'

    steps:
      - uses: actions/checkout@v2

      - name: Build images
        run: |
          docker build -t vafrcor/complex-client ./client
          docker build -t vafrcor/complex-nginx ./nginx
          docker build -t vafrcor/complex-server ./server
          docker build -t vafrcor/complex-worker ./worker

      - name: Log into Docker Hub registry
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_ID }}" --password-stdin

      - name: Push images
        run: |
          docker push vafrcor/complex-client
          docker push vafrcor/complex-nginx
          docker push vafrcor/complex-server
          docker push vafrcor/complex-worker
